# CM50270 Reinforcement Learning
## Coursework Part 1: Value Iteration

In this exercise, you will implement the value iteration algorithm for three closely related, but different, gridworld environments.

**Total number of marks:** 20 marks.

**What to submit:** Your completed Jupyter notebook (.ipynb file) which should include **all** of your source code. Please **do not change the file name or compress/zip your submission**. Please do not include any identifying information on the files you submit. This coursework will be marked **anonymously**.

**Where to submit:** CM50270 Moodle Page.

You are required to **work individually**. You are welcome to discuss ideas with others but you must design your own implementation and **write your own code**.

**Do not plagiarise**. Plagiarism is a serious academic offence. For details on what plagiarism is and how to avoid it, please visit the following webpage: http://www.bath.ac.uk/library/help/infoguides/plagiarism.html

If you are asked to use specific variable names, data-types, function signatures and notebook cells, **please ensure that you follow these instructions**. Not doing so will cause the automarker to reject your work, and will assign you a score of zero for that question. **If the automarker rejects your work because you have not followed the instructions, you may not get any credit for your work**.

Please **do not use any non-standard, third-party libraries** apart from numpy and matplotlib. **If we are unable to run your code because you have used unsupported external libraries, you may not get any credit for your work.**

Please remember to **save your work regularly**.

Please be sure to **restart the kernel and run your code from start-to-finish** (Kernel → Restart & Run All) before submitting your notebook. Otherwise, you may not be aware that you are using variables in memory that you have deleted.

Your total runtime must be less than **1 minute** on the University's computers. Otherwise, you may not get credit for your work. You can run your code on the university's computers remotely using [UniDesk](https://bath.topdesk.net/tas/public/ssp/content/detail/knowledgeitem?unid=ff3266344c1d4eb2acb227cc9e3e1eee).

## Introduction
In this coursework, you will implement the Value Iteration algorithm to compute an optimal policy for three different (but closely related) Markov Decision Processes. For your reference, the pseudo-code for the Value Iteration algorithm is reproduced below from the textbook (Reinforcement Learning, Sutton & Barto, 2018, pp. 83).

<img src="images/value_iteration.png" style="width: 800px;"/>

Please note the following about the pseudo-code: The set $\mathcal{S}$ contains all non-terminal states, whereas $\mathcal{S}^+$ is the set of all states (terminal and non-terminal). The symbol $r$ represents the immediate reward on transition from state $s$ to the next state $s'$ via action $a$. 

<img src="images/bombs and gold numbers.png" style="width: 300px;" align="left" caption="Figure 1"/>

The three problems you will solve use variants of the gridworld environment shown on the left. You should be familiar with this kind of environment from the lectures. The grid squares in the figure are numbered as shown. In all exercises, the following are true: 

**Actions available:** The agent has four possible actions in each grid square. These are *west*, *north*, *south*, and *east*. If the direction of movement is blocked by a wall (for example, if the agent executes action south at grid square 1), the agent remains in the same grid square. 

**Collecting gold:** On its first arrival at a grid square that contains gold (from a neighbouring grid square), the agent collects the gold. Note that, in order to collect the gold, the agent needs to transition into the grid square (containing the gold) from a different grid square.

**Hitting the bomb:** On arrival at a grid square that contains a bomb (from a neighbouring grid square), the agent activates the bomb. 

**Terminal states:** The game terminates when all gold is collected or when the bomb is activated. In Exercises 1 and 2, you can define terminal states to be grid squares 18 and 23. In Exercise 3, you will need to define terminal state(s) differently.


### Instructions ###
Set parameter $\theta$ to $1 \times 10 ^{-10}$. You can express that as `1e-10` in Python. 

Set all initial state values $V(s)$ to zero.

Do not use discounting (that is, set $\gamma=1$).

Use the following reward function: $-1$ for each navigation action (including when the action results in hitting the wall), an additional $+10$ for collecting each piece of gold, and an additional $-10$ for activating the bomb. For example, the immediate reward for transitioning into a square with gold (from a neighbouring grid square) is $-1 + 10 = +9$. 

## Exercise 1: Deterministic Environment (0 Marks)

In this exercise, the agent is able to move in the intended direction with certainty. For example, if it executes action _north_ in grid square 0, it will transition to grid square 5 with probability 1. In other words, we have a deterministic environment.

Compute the optimal policy using Value Iteration. 

Your need to produce two one-dimensional numpy arrays with names `policy` and `v`. Both arrays should have a length of 25, with the element at index $i$ representing grid cell $i$ (see figure above). Both arrays should be accessible in the "solution cell" below!

The array `policy` should be a numpy array of strings that specifies an optimal action at each grid location. Please use the abbreviations `"n"`, `"e"`, `"s"`, and `"w"` for the four actions. As an example, the value of `policy` at index `0` needs to give `"n"`, if _north_ is an optimal action in cell 0. The policy for a terminal state can be any action. If there are multiple optimal actions from a state, any optimal action will be considered as a correct answer. 

The array `v` should be an array of floats that contains the expected return at each grid square (that is, the state value under the optimal policy).

In [1]:
import numpy as np

class Gridworld:
    def __init__(self):
        
        # Initializing environmental variables to be used
        self.num_rows = 5
        self.num_cols = 5
        self.num_fields = self.num_cols * self.num_rows
        self.gold_reward = 10
        self.bomb_reward = -10
        self.gold_positions = np.array([23])
        self.bomb_positions = np.array([18])

        self.rewards = np.zeros(shape=self.num_fields)
        self.rewards[self.bomb_positions] = self.bomb_reward
        self.rewards[self.gold_positions] = self.gold_reward

        self.actions = ["n", "e", "s", "w"]
        self.num_actions = len(self.actions)

        
    def make_step(self, state, curr_action, model):
        
        
        # Choosing model for the different exercises and changing transition probabilities
        if model == 'stochastic': 

            action_rewards = np.zeros(self.num_actions)
            next_states = np.zeros(self.num_actions, dtype=int)
            
            action_probabilities = np.zeros(self.num_actions)
            action_probabilities.fill(0.05)
            action_probabilities[environment.actions.index(curr_action)] = 0.85

        elif model == 'deterministic':
             
            action_rewards = np.zeros(self.num_actions)
            next_states = np.zeros(self.num_actions, dtype=int)
            
            action_probabilities = np.zeros(self.num_actions)
            action_probabilities[environment.actions.index(curr_action)] = 1
            
        else:
            raise ValueError('Model was mis-specified!')

        
        # Calculating reward and getting new position for all the actions
        for action_index in range(self.num_actions):
    
            # Determine new position and check whether the agent hits a wall.
            old_position = state
            new_position = state
            if self.actions[action_index] == "n":
                candidate_position = old_position + self.num_cols
                if candidate_position < self.num_fields:
                    new_position = candidate_position
            elif self.actions[action_index] == "e":
                candidate_position = old_position + 1
                if candidate_position % self.num_cols > 0:  # The %-operator denotes "modulo"-division.
                    new_position = candidate_position
            elif self.actions[action_index] == "s":
                candidate_position = old_position - self.num_cols
                if candidate_position >= 0:
                    new_position = candidate_position
            elif self.actions[action_index] == "w":  # "LEFT"
                candidate_position = old_position - 1
                if candidate_position % self.num_cols < self.num_cols - 1:
                    new_position = candidate_position
            else:
                raise ValueError('Action was mis-specified!')

            # Calculate reward
            action_rewards[action_index] = self.rewards[new_position]
            action_rewards[action_index] -= 1
            
            next_states[action_index] = new_position
            
        
        return action_rewards, next_states, action_probabilities
    

In [2]:
def play(environment, model):
    
    delta = 1
    theta=1e-10 
    gamma=1.0
    
    policy = np.empty(25, dtype=str)
    policy[:] = "n"
    v = np.zeros(25)

    # Finding Optimal Value Function Using Value Iteration algorithm
    while delta > theta:
        delta = 0

        for state in range(environment.num_fields):
            if state not in [18,23]:
                u = v[state]
                
                sum_array= np.zeros(environment.num_actions)  
                
                # Using Bellman equation
                for action in environment.actions:
                    action_rewards, next_states, action_probabilities = environment.make_step(state, action, model)                    
                    sum_array[environment.actions.index(action)] = np.sum(action_probabilities*(action_rewards + gamma*v[next_states]))
                    
                
                v[state] = np.max(sum_array)
                delta = max(delta, np.abs(u - v[state]))
    
    
    # Extracting Policy from value function only once (since it is not a policy iteration)
    for state in range(environment.num_fields):
        if state not in [18,23]:

            sum_array= np.zeros(environment.num_actions)
            
            for action in environment.actions:
                action_rewards, next_states, action_probabilities = environment.make_step(state, action, model)                    
                sum_array[environment.actions.index(action)] = np.sum(action_probabilities*(action_rewards + gamma*v[next_states]))

            optA_index = np.argmax(sum_array)
            policy[state] = environment.actions[optA_index]
    
    
    return v, policy

In [3]:
# Please write your code for Exercise 1 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm. We will mark your coursework by checking the values of 
# the variables policy and v in the hidden test cell further below. Do NOT delete this cell.

environment = Gridworld()
# Using a deterministic model for Exercise 1
v, policy = play(environment, 'deterministic')
print(np.flip(v.reshape((5, 5)), 0))
print(np.flip(policy.reshape((5, 5)), 0))

[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]


**Example Test Cell**

In the code cell below, we have provided an example of the type of test code that we will use to mark your work. In these tests, we first check that your `policy` and `v` variables are of the correct type, and then check that their values match the solution. In the future, the test code will be hidden from you.

You must not delete or modify test cells in any way - any modifications you do make will be overwritten at run-time.

In [4]:
# DO NOT DELETE OR MODIFY THIS CELL!
# Your code for Exercise 1 is tested here.

import numpy as np

# We're giving you the solution values for Exercise 1, but not telling you how to compute them!
solution_values = [3.0, 4.0, 5.0, 4.0, 5.0,
                   4.0, 5.0, 6.0, 5.0, 6.0,
                   5.0, 6.0, 7.0, 6.0, 7.0,
                   6.0, 7.0, 8.0, 0.0, 8.0,
                   7.0, 8.0, 9.0, 0.0, 9.0]
solution_values = np.array(solution_values)

# We're giving you the solution policy for Exercise 1, but not telling you how to compute it!
solution_policy = [
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'e', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'e', 'e', 'e', 'n', 'w',]
solution_policy = np.array(solution_policy)

# Check that policy and v are numpy arrays.
assert(isinstance(policy, np.ndarray))
assert(isinstance(v, np.ndarray))

# Check correct shapes of numpy arrays.
assert(policy.shape == (25, ))
assert(v.shape == (25, ))

# Check whether the numpy arrays have the correct data types.
assert(np.issubdtype(policy.dtype, np.unicode_)) # policy.dtype should be '<U1'
assert(np.issubdtype(v.dtype, np.float64))

# Check whether policy contains only "n", "w", "s", or "e" values.
assert(np.all(np.isin(policy, np.array(["n", "w", "s", "e"]))))

# Print student's solution and true solution for easier comparison / spotting of errors.
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))
print("Solution policy:")
print(np.flip(solution_policy.reshape((5, 5)), 0))

print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("Solution v:")
print(np.flip(solution_values.reshape((5, 5)), 0))

# Compare policy (only on states that have a single optimal direction).
states_to_check =  np.array([4, 9, 14, 17, 19, 20, 22, 24])
np.testing.assert_array_equal(policy[states_to_check], solution_policy[states_to_check])

# Compare state_values (also for terminal states --- they have to be zero!).
states_to_check = np.delete(np.arange(25), np.array([18, 23]))
np.testing.assert_array_almost_equal(v[states_to_check], solution_values[states_to_check], decimal=3)

Student's policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]
Solution policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]
Student's v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]
Solution v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]


## Exercise 2: Stochastic Environment (12 Marks)

In this exercise, we introduce stochasticity into the environment. Now, the agent is not always able to execute its actions as intended.

With probability 0.8, the agent moves as intended. However, with probability 0.2, it moves in a random direction.

For example, from grid square 0, if the agent tries to move north, with probability 0.8 the action will work as intended. But with probability 0.2, the agent's motor control system will move it in a random direction (including north). So, it will randomly try to move west, east, north or south with probability 0.05 each. Notice that the total probability of moving to square 5 (as intended) is 0.8 + 0.05 = 0.85.
 
Compute the optimal policy using Value Iteration.

Your value iteration method should output two one-dimensional numpy arrays with names `policy` and `v`, as in Exercise 1.

In [5]:
# Please write your code for Exercise 2 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm. We will mark your coursework by checking the values of 
# the variables policy and v in the hidden test cell further below. Do NOT delete this cell.

environment = Gridworld()
# Using a stochastic model for Exercise 2
v, policy = play(environment, 'stochastic')
print(np.flip(v.reshape((5, 5)), 0))
print(np.flip(policy.reshape((5, 5)), 0))

[[6.04169329 7.28756636 8.61359951 0.         8.69262311]
 [4.86185111 5.99087587 6.37082431 0.         6.46721593]
 [3.67550938 4.69621388 4.99441863 3.2189158  5.10250988]
 [2.48699534 3.40945989 3.66922967 2.64122933 3.78610115]
 [1.35979208 2.19733672 2.42878751 1.57272161 2.55202451]]
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']]


In [6]:
# DO NOT DELETE OR MODIFY THIS CELL!
# Your code for Exercise 2 is tested here.


## Exercise 3: Stochastic Environment with Two Pieces of Gold (8 marks)

<img src="images/bomb and two gold.png" style="width: 300px;" align="left" caption="Figure 1"/> In this exercise, we have modified the stochastic environment presented in exercise 2. A second piece of gold has been placed on grid square 12. The terminal state is reached only when **all** pieces of gold are collected or when the bomb is activated.

Compute the optimal policy for this altered environment using Value Iteration.

Hint: You will need to change your state representation in order to account for the additional piece of gold.

Your method should output two one-dimensional numpy arrays with names `policy` and `v`, as in the previous exercises. These arrays should specify the expected return and an optimal policy at the corresponding grid sqaure **before any pieces of gold are collected or a bomb is activated.** 

In [7]:
# Declaring a new gridworld class
class Gridworld2:
    def __init__(self, dimension):
        self.num_rows = 5
        self.num_cols = 5
        self.num_fields = self.num_cols * self.num_rows
        self.gold_reward = 10
        self.bomb_reward = -10
        
        # Gold positions in each "dimenion" assuming in 1 and 2 that 1 of the gold has been collected
        if dimension == 0:
            self.gold_positions = np.array([12,23])
        elif dimension == 1:
            self.gold_positions = np.array([23])
        elif dimension == 2:
            self.gold_positions = np.array([12])
        
        self.bomb_positions = np.array([18])

        self.rewards = np.zeros(shape=self.num_fields)
        self.rewards[self.bomb_positions] = self.bomb_reward
        self.rewards[self.gold_positions] = self.gold_reward

        self.actions = ["n", "e", "s", "w"]
        self.num_actions = len(self.actions)

        
    def make_step(self, state, curr_action, model):
        
        # Same methods as in Exercises 1 and 2
        
        if model == 'stochastic': 

            action_rewards = np.zeros(self.num_actions)
            next_states = np.zeros(self.num_actions, dtype=int)
            
            action_probabilities = np.zeros(self.num_actions)
            action_probabilities.fill(0.05)
            action_probabilities[environment.actions.index(curr_action)] = 0.85

        elif model == 'deterministic':
             
            action_rewards = np.zeros(self.num_actions)
            next_states = np.zeros(self.num_actions, dtype=int)
            
            action_probabilities = np.zeros(self.num_actions)
            action_probabilities[environment.actions.index(curr_action)] = 1
            
        else:
            raise ValueError('Model was mis-specified!')

            
        for action_index in range(self.num_actions):
    
            # Determine new position and check whether the agent hits a wall.
            old_position = state
            new_position = state
            if self.actions[action_index] == "n":
                candidate_position = old_position + self.num_cols
                if candidate_position < self.num_fields:
                    new_position = candidate_position
            elif self.actions[action_index] == "e":
                candidate_position = old_position + 1
                if candidate_position % self.num_cols > 0:  # The %-operator denotes "modulo"-division.
                    new_position = candidate_position
            elif self.actions[action_index] == "s":
                candidate_position = old_position - self.num_cols
                if candidate_position >= 0:
                    new_position = candidate_position
            elif self.actions[action_index] == "w":  # "LEFT"
                candidate_position = old_position - 1
                if candidate_position % self.num_cols < self.num_cols - 1:
                    new_position = candidate_position
            else:
                raise ValueError('Action was mis-specified!')

            
            # Minor change in rewards to prevent getting gold when in a gold state and hitting a wall.
            if old_position != new_position:
                action_rewards[action_index] = self.rewards[new_position]
            
            action_rewards[action_index] -= 1
            
            next_states[action_index] = new_position
            
        
        return action_rewards, next_states, action_probabilities

In [8]:
def play2(model):
    
    delta = 1
    theta=1e-10 
    gamma=1
    
    policy = np.empty(75, dtype=str)
    policy[:] = "n"
    v = np.zeros(75)

    # Finding Optimal Value Function
    while delta > theta:
        delta = 0

        for state in range(75):
            # Declaring the terminal states that can be found in all 3 "dimensions"
            if state not in [18,43,68,48,62]:

                # Changing the gold positions
                if state==0:
                    environment = Gridworld2(0)
                elif state==25:
                    environment = Gridworld2(1)
                elif state==50:
                    environment = Gridworld2(2)
                    
                u = v[state]
                                
                sum_array= np.zeros(environment.num_actions)  
                
                # Storing the "dimension" and state to calculate back the actual position
                dimension = state//25
                dimension_state = state%25
                                
                for action in environment.actions:
                    
                    action_rewards, next_states, action_probabilities = environment.make_step(dimension_state, action, model)
                    
                    # Changing dimensional state when finding a gold state
                    next_states = next_states + dimension*25
                    next_states = np.where(next_states==12, 37, next_states)
                    
                    # Preventing hitting a wall to change to "dimension" of the state
                    if state != 23:
                        # Changing dimensional state when finding a gold state
                        next_states = np.where(next_states==23, 73, next_states)
                    
                    sum_array[environment.actions.index(action)] = np.sum(action_probabilities*(action_rewards + gamma*v[next_states]))
                    
                v[state] = np.max(sum_array)
                delta = max(delta, np.abs(u - v[state]))
            

    # Combination of initial method and this function's method to calclate the optimal policy
    for state in range(75):
        if state not in [18,43,68,48,62]:

            if state==0:
                environment = Gridworld2(0)
            elif state==25:
                environment = Gridworld2(1)
            elif state==50:
                environment = Gridworld2(2)

            sum_array= np.zeros(environment.num_actions)  

            dimension = state//25
            dimension_state = state%25
            
            for action in environment.actions:

                action_rewards, next_states, action_probabilities = environment.make_step(dimension_state, action, model)

                next_states = next_states + dimension*25
                next_states = np.where(next_states==12, 37, next_states)
                
                if state != 23:
                    next_states = np.where(next_states==23, 73, next_states)
                    
                sum_array[environment.actions.index(action)] = np.sum(action_probabilities*(action_rewards + gamma*v[next_states]))


            optA_index = np.argmax(sum_array)
            policy[state] = environment.actions[optA_index]
            

    v = v[:25]
    policy = policy[:25]
    
    return v, policy


In [9]:
# Please write your code for Exercise 3 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm. We will mark your coursework by checking the values of 
# the variables policy and v in the hidden test cell further below. Do NOT delete this cell.

# Stochastic but using the methods created for Exercise 3
v, policy = play2('stochastic')
print(np.flip(v.reshape((5, 5)), 0))
print(np.flip(policy.reshape((5, 5)), 0))

[[10.65103994 11.79603433 13.00848756 10.74288293 12.97048714]
 [11.1861353  12.32932372 12.5121464   0.         10.61568556]
 [12.28702748 13.59365638 12.48072659 12.41930416 11.19974428]
 [11.17522837 12.35165962 13.59092292 12.28122217 11.051285  ]
 [10.06409806 11.17488271 12.28045984 11.10816476  9.99389366]]
[['e' 'e' 'e' 'w' 'w']
 ['e' 's' 's' 'n' 'n']
 ['e' 'e' 'w' 'w' 'w']
 ['e' 'n' 'n' 'w' 'w']
 ['n' 'n' 'n' 'n' 'w']]


In [10]:
# DO NOT DELETE OR MODIFY THIS CELL!
# Your code for Exercise 3 is tested here.
